CREATE TABLE IF NOT EXISTS REF_RESSOURCE (
  ID_REF_RESSOURCE INTEGER PRIMARY KEY,
  CODE             VARCHAR(30),
  CONSOLIDABLE     INTEGER
);

CREATE TABLE IF NOT EXISTS REF_PROPRIETE_PHYSIQUE (
  ID_REF_PROPRIETE_PHYSIQUE INTEGER PRIMARY KEY,
  CODE                      VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS CLIENT (
  ID_CLIENT INTEGER PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS SITE (
  ID_SITE   INTEGER PRIMARY KEY,
  ID_CLIENT INTEGER
);

CREATE TABLE IF NOT EXISTS POINT_MESURE (
  ID_POINT_MESURE        INTEGER PRIMARY KEY,
  ID_POINT_MESURE_PARENT INTEGER,
  ID_REF_RESSOURCE       INTEGER,
  ID_SITE                INTEGER
);

CREATE TABLE IF NOT EXISTS CANAL (
  ID_CANAL                  INTEGER PRIMARY KEY,
  ID_CANAL_ENTREPOT         INTEGER,
  ID_POINT_MESURE           INTEGER,
  ID_REF_PROPRIETE_PHYSIQUE INTEGER,
  DATE_SUPPRESSION DATE
);
