create table ETP_CANAL
(
  ID_CANAL                     NUMBER              not null
    constraint PK_ETP_CANAL
    primary key,
  IDENTIFIANT_SOURCE           VARCHAR2(128),
  IDENTIFIANT_CIBLE            VARCHAR2(128),
  RESOLUTION_ORIGINE_SECONDES  NUMBER,
  RESOLUTION_CIBLE_SECONDES    NUMBER,
  BOUCHAGE_TROUS               NUMBER(1),
  CODE_ALGORITHME_BOUCHAGE     VARCHAR2(64),
  COEFFICIENT                  NUMBER,
  ID_REF_PROPRIETE_PHYSIQUE    NUMBER,
  ID_REF_TYPE_DONNEES          NUMBER,
  VALEUR_MIN                   NUMBER,
  VALEUR_MAX                   NUMBER,
  COEFFICIENT_PCS              NUMBER,
  COEFFICIENT_PTA              NUMBER,
  IDENTIFIANT_EQUIPEMENT       VARCHAR2(64),
  GESTIONNAIRE_RESEAU          VARCHAR2(32),
  TYPE_FLUX                    VARCHAR2(32),
  DATE_CREATION                DATE,
  DATE_MODIFICATION            DATE,
  DATE_DESACTIVATION           DATE,
  DATE_UTC_FIN_VENTILATION     DATE,
  ID_CANAL_TEMP_DJU            NUMBER,
  ID_STATION_METEO_DJU         NUMBER,
  BASE_CALCUL_DJU              NUMBER,
  EST_CANAL_INDEX              NUMBER(1) default 0 not null,
  ID_REF_LISTE_FLUX            NUMBER,
  PRODUCTION                   NUMBER(1) default 0 not null,
  DATE_PREMIERE_DONNEE_UTC     DATE,
  DATE_DERNIERE_DONNEE_UTC     DATE,
  ID_STATION_METEO             NUMBER,
  DATE_DEBUT_MODIF_DONNEES_UTC DATE,
  DATE_FIN_MODIF_DONNEES_UTC   DATE
);

create sequence SEQ_ETP_CANAL
  nocache;

CREATE TABLE REF_PROPRIETE_PHYSIQUE
(
  ID_REF_PROPRIETE_PHYSIQUE NUMBER       NOT NULL
    CONSTRAINT PK_REF_PROPRIETE_PHYSIQUE
    PRIMARY KEY,
  CODE                      VARCHAR2(32) NOT NULL,
  LIBELLE                   VARCHAR2(64),
  TYPE_AGREGATION           VARCHAR2(64),
  ID_REF_RESSOURCE          NUMBER,
  CONSOLIDABLE              NUMBER(1)
);


CREATE TABLE REF_TYPE_DONNEES
(
  ID_REF_TYPE_DONNEES NUMBER       NOT NULL
    CONSTRAINT PK_REF_TYPE_DONNEES
    PRIMARY KEY,
  CODE                VARCHAR2(16) NOT NULL,
  LIBELLE             VARCHAR2(64)
);